### ISSUE TITLE
Feature Request. reference images

### ISSUE THREAD

**Issue by captain-rainbow** [nkallen/plasticity#27] opened 2022-03-05 14:42 UTC
Being able to add in reference images is a crucial tool for modelling properly. I am loving it but this is basically what hinders me from creating lowpoly models using this tool.

**Comment by robtherobot12** [comment] 2022-03-07 08:49
I think it would be very useful, but a good alternative in the meanwhile is PureRef.

**Comment by dumblob** [comment] 2022-03-16 20:24
Duplicate of https://github.com/nkallen/plasticity/issues/25 but with a better name and suggestions :wink:.

**Comment by dannyasetvisions** [comment] 2022-03-18 12:05
I think this would be a really good feature. Do a quick drawing/sketch and then pop it in the viewport and model over. 
I tend to draw out my ideas in elevation and perspective first. +1 for this feature

**Comment by kamilszarama** [comment] 2022-04-16 23:18
As much as I love PureRef it is not a replacement for reference planes in software as those are useful for creating accurately sized models. I do think it's a must have for a piece of software that is marketed as "CAD for artists".

**Comment by thizzhead** [comment] 2022-04-16 23:19
As much as I love PureRef it is not a replacement for reference planes in software as those are useful for creating accurately sized models. I do think it's a must have for a piece of software that is marketed as "CAD for artists".

**Closed** 2022-06-24 18:34 UTC
Labels: no-issue-activity
