### ISSUE TITLE
How do I build and run this project?

### ISSUE THREAD

**Issue by lodenrogue** [nkallen/plasticity#53] opened 2022-03-18 01:30 UTC

**Comment by Ramkumar47** [comment] 2022-03-18 04:04
yes, i am trying to find that as well. i am under Linux Ubuntu.. i would like to try this out.. could u plz post the compilation instructions?

**Comment by Techwizz-somboo** [comment] 2022-03-18 05:34
Duplicate of issue #30. You can't build it. You will have to use a closed source lib that will be released with the paid version of the app.

**Comment by lodenrogue** [comment] 2022-03-18 13:53
So basically this? 

https://opensource.org/court-affirms-its-false-advertising-to-claim-software-is-open-source-when-its-not

**Comment by Techwizz-somboo** [comment] 2022-03-19 01:10
> So basically this?
> 
> https://opensource.org/court-affirms-its-false-advertising-to-claim-software-is-open-source-when-its-not

Nick never claimed it's open source. He said it's partially open source. You will be able to build it on your own after release after you buy the software which will come with the library.

**Comment by Techwizz-somboo** [comment] 2022-03-19 01:54
Guys, it's now in the AUR! It's named `plasticity-bin`.

**Comment by Ramkumar47** [comment] 2022-03-19 03:47
oh.. nice.. some genius has put it on AUR

**Closed** 2022-03-21 23:14 UTC
